### ISSUE TITLE
No benifits for deploying resnext101

### ISSUE THREAD

**Issue by LeonWlw** [mingfeima/convnet-benchmark-py#1]
I run the script for deploying resnext101, but I can't get any gains with mkldnn and cache-weight.
Here is my runtime information:
./run.sh --inference --single
inference only
using single batch size
using OMP_NUM_THREADS=32
using KMP_AFFINITY=granularity=fine,compact,1,0
using KMP_BLOCKTIME=1

Running on device:  Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz
Running on torch: 1.4.0
Running on torchvision: 0.5.0

ModelType: resnext101, Kernels: nn Input shape: 1x3x224x224
nn                                :forward:     236.60 (ms)       4.23 (imgs/s)
nn                             :backward:         0.00 (ms)
nn                                 :update:         0.00 (ms)
nn                                     :total:     236.60 (ms)       4.23 (imgs/s)

--------
./run.sh --inference --single --mkldnn
ModelType: resnext101, Kernels: nn Input shape: 1x3x224x224
nn                                :forward:     242.39 (ms)       4.13 (imgs/s)
nn                             :backward:         0.00 (ms)
nn                                 :update:         0.00 (ms)
nn                                     :total:     242.39 (ms)       4.13 (imgs/s)

--------
./run.sh --inference --single --mkldnn --cache-weight
ModelType: resnext101, Kernels: nn Input shape: 1x3x224x224
nn                                :forward:     236.43 (ms)       4.23 (imgs/s)
nn                             :backward:         0.00 (ms)
nn                                 :update:         0.00 (ms)
nn                                     :total:     236.43 (ms)       4.23 (imgs/s)

**There is no benifits with mkldnn or cache-weight. I install pytorch by pip, is it the case that build pytorch without icc?**
Here is my pytorch built informations:
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
---------
@mingfeima Can u help me to find why I can't get the benifits that you mentioned？

**Comment by mingfeima** [comment]
Thanks for pointing this out. This benchmark is a little bit outdated and i just renewed it.
You can see perf updates from the README.md and by the way i suggest you switch to latest PyTorch (binary release or nightly build both OK).
Also for inference, it is recommended to use `jemalloc` or `tcmalloc` with `numactrl` on a single numa node (which means a single socket for Intel Xeon CPU), you can take `run.sh` as a reference.

the `_mkldnn` layout means that both activation (input and output) and feature maps (weights) will be in mkldnn blocked format during the propagation. this plan has a flaw that in case the network comprises an operator that does not support mkldnn blocked format, you have to convert it back to plain format **manually**. So somewhat unfriendly to use...

we have be working on channels last (nhwc) format and hopefully this will be ready soon. In CL format, activation will always be plain format (nhwc) so you don't have to worry about the blocked-plain format conversion in case of a mkldnn-non-supported operator. the idea is [here](https://gist.github.com/mingfeima/595f63e5dd2ac6f87fdb47df4ffe4772#memory-format-is-all-that-matters). i will renew this benchmark once this is fully available.

**Comment by LeonWlw** [comment]
Thanks for your quick replay. I rerun this benchmark for resnext101. Here is my informations:

Running on device:  Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz
Running on torch: 1.6.0+cpu
Running on torchvision: 0.7.0+cpu

tcmalloc | numactl | mkldnn | jit | (ms)
× | × | × | × | 124
√ | × | × | × | 150
× | √ | × | × | 97
√ | √ | × | × | 121
× | × | √ | × | 120
× | √ | √ | × | 97
× | √ | √ | √ | 97
√ | √ | √ | √ | 121

I can find that only numactl useful, tcmalloc harmful, mkldnn and jit still useless.
Did u build torch 1.7.0a0+7cc6540 from source code by intel c compiler?(My torch was installed by pip from 1.6.0 release version) Can u give some advise to help me find out why mkldnn and jit useless in my situation？

**Comment by mingfeima** [comment]
I need more info to debug this issue. Please test `--mkldnn` on and off with mkldnn verbose enabled:
```bash
MKLDNN_VERBOSE=2 ./run.sh --inference --single
MKLDNN_VERBOSE=2 ./run.sh --inference --single --mkldnn
```
The verbose will print every execution timing info of mkldnn operators, so the log is somehow overwhelming. You can reduce the number of iterations, say 10, so as to reduce the size of the final log. If the log is still too long, please send me by email mingfei.ma@intel.com

By the way, this issue should have nothing to do with compiler (icc doesn't compile yet). I tried public release '1.6.0+cpu' and still  got similar result as my local '1.7.0a0+7cc6540'.

**Comment by LeonWlw** [comment]
@mingfeima You're so kind to help me. My issue is not really using mkldnn flag. Then I can get the results as expected.Thanks again!
